spring:
  application:
    name: lucene-slave
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: "2m"


server:
  port: 8082
  http2:
    enabled: true

grpc:
  port: 50052
  master-host: localhost
  master-port: 50050

#    port: ${server.port}
lucene:
  index-dir: /home/search/index2
