spring:
  application:
    name: lucene-slave
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: "2m"


server:
  port: 8084
  http2:
    enabled: true

grpc:
  port: 50054
  master-host: localhost
  master-port: 50050

#    port: ${server.port}
lucene:
  path: /home/search/index4
