spring:
  application:
    name: lucene-master
  lifecycle:
    timeout-per-shutdown-phase: "2m"
  sqlite:
    url: easy.db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
  http2:
    enabled: true

grpc:
  port: 50050

